### ISSUE TITLE
[map] kleinere bugs im SVG

### ISSUE THREAD

**Issue by lbenedix** [nbi-opendata/videbligo#15]
- im Osten fehlt ein Schnippsel, der zu Treptow-Köpenick gehört
  - ![Rahnsdorf1](https://d2oawfjgoy88bd.cloudfront.net/52ac4783888b9d160275e338/52ac479c888b9d16034ca1c3/548cd5fe00779135596f9de2.png?Expires=1418602374&Signature=TxJoBNvCuRMQmOK2q4M0yN8rWLkgDm0fGjTzDa5LgR02RHr3zVm2Aj4YJkn3uNrHMkeaWoNNrbDoxM1kkL3Yim5JZOxFV4u2EvZqZ6EtrVhF5GJ980aEPfw4tq5adLnrkEu2-810m3rSjd5aLnd-Nr9SIKlP16asqP8gvuHJa91UPF6R3A105ebYwfbN4wVtOz1UrcKuPDlNuydZScfTWKxEDGEZRepghwtjt~tPbVLFgp67hlThqwiIVLR2PO9dJPV8UlqjMDdqF9OhmIaYj4akXYuOK4eVw6w~efNz-UkZiuVxRjEM7LrnzBT9O7IwPGe5b4ySUordtVwUYhALcg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
  - ![Rahnsdorf2](https://d2oawfjgoy88bd.cloudfront.net/52ac4783888b9d160275e338/52ac479c888b9d16034ca1c3/548cd65400779135586fae43.png?Expires=1418602461&Signature=S2drk~wXuM0WUP2j4XiUmYpcy3~GkvYj46F22t4xApYbVDwGKEfadrPec5nefFltEj~sOezUCwtj9uTHDrMBhJc7GnSNGIOSBtRUeUuV6DcqjieGk-afl2IdsThAmeBz39V1lBcXJFMqBFUZkJoCG4gygp0Byd5UPwJIKaHbCrdztVO7gq0fl3q5I5CaxstOKzpByb4HQCw~PtLCNHA2DLI9184-6XC8Vrja8F7yi7PjI6IzdjFPGJusV5~U6yWaVJ9R-9bBKGRP62-DDEZ8ql2IKPtkT5Rdv2eV6tdqf3LtZbY8TsuwPOYWrFVNwd~ce8qZ2dU~BFVzCpC8qmbwtw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
- bei dem Bären, läuft irgendwas ganz schön falsch mit dem Arm, dem Körper und der Zunge
  - ![Bär1](https://api.monosnap.com/image/download?id=3S9H0kOIqprATSaFaV8TFByea6VSpr)
  - ![Bär2](https://api.monosnap.com/image/download?id=8Uk7YCqm1eZdVSyKwgtgkMSTDWnmTZ)

**Comment by lbenedix** [comment]
Im Westen ist auch etwas komisch, da fehlt ein kleiner schnippsel unten links (vermutlich durch die breiten weißen Umriss-Linien):

![Wannsee1](https://api.monosnap.com/image/download?id=tjch00XGhZ1Mc8eQ4TisN97KNdi5eL)

![Wannsee2](https://api.monosnap.com/image/download?id=uAcg6J7fQloyYFXvQa97BNCvpfJkSu)

**Comment by ktugan** [comment]
done by norman and kim
