### ISSUE TITLE
Map Background 

### ISSUE THREAD

**Issue by hanintalal** [nbi-opendata/videbligo#30]
der Hintergrund der Karte ist gelblich

**Comment by ClownCombat** [comment]
Wo ist der Hintergrund gelblich? Kannst du bitte auch ein Foto schicken?

**Comment by hanintalal** [comment]
bei mir kommt der Hintergrund ein bisschen Gelblich ,also nicht so ganz weiß :)  
die Fotos schicke ich gleich  

## 

hanin
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by hanintalal** [comment]
ich glaube mann kann die Nummer der Farbe vergleichen , damit ihr weißt , welche Farbe hat der Hintergrund  

## 

hanin
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
