### ISSUE TITLE
Karte  Verbesserung 

### ISSUE THREAD

**Issue by hanintalal** [nbi-opendata/videbligo#31]
ein ganz klein Teil unten und rechts an der Karte ist nicht sichtbar ,man kann es nach dem Auswahl erkennen .Ich werde den Foto im Slack schicken .

**Comment by hanintalal** [comment]
Noch einen Vorschlag , der schwatze Rand dünner machen , dann wird die Karte schöner .

**Comment by ktugan** [comment]
Prio Low
