### ISSUE TITLE
Zeitperiode widget

### ISSUE THREAD

**Issue by hanintalal** [nbi-opendata/videbligo#32]
1- In Zeitperiode Widget ( neu stellen oder Rücksitzen statt reset ) 
2- Die Zahl auf der X Achse wird bei mache Ergebnisse von dem Wort reset verdeckt .
3-also vielleicht der Name des x Achses wird von dem ersten Balken auch verdeckt .

**Comment by hanintalal** [comment]
das 3. Problem scheint auch vielleicht bei Letzte Änderungschart Widget

**Comment by ktugan** [comment]
nutzung von dc js und damit obselet
