### ISSUE TITLE
[Last modified] Deutsche Sprache

### ISSUE THREAD

**Issue by ktugan** [nbi-opendata/videbligo#47]
Die Monate in dem Date Widget sind aktuell Englisch. Müssten Deutsch sein

**Comment by wojtuch** [comment]
http://stackoverflow.com/questions/19274464/how-to-make-localization-on-months-days-for-d3js

**Comment by wojtuch** [comment]
Das Problem halbwegs gefixt.
Halbwegs, weil momentan **nur** Monate auf der Achse angezeigt werden, ohne Jahre dazwischen, siehe Bilder:

![screen shot 2015-01-22 at 11 03 45](https://cloud.githubusercontent.com/assets/1650824/5853713/6cf59298-a226-11e4-931e-b1715b829ec9.png)

![screen shot 2015-01-22 at 11 04 01](https://cloud.githubusercontent.com/assets/1650824/5853712/6cf59072-a226-11e4-8aee-f34d3a195a23.png)

Vielleicht finde ich passende Formatierung, die DC.js benutzt und somit wird das Problem komplett behoben.

**Comment by wojtuch** [comment]
funktioniert leider nicht mehr wenn man tief genug reinzoomt
