### ISSUE TITLE
[result] titel anklickbar zum aufklappen

### ISSUE THREAD

**Issue by ktugan** [nbi-opendata/videbligo#57]

**Comment by lbenedix** [comment]
implemented in develop

**Comment by wojtuch** [comment]
Nun kann man nur aufklappen, indem man auf den Titel oder den Pfeil klickt 

Leider kann man nicht mehr die Fläche neben dem Link dazu benutzen (weder fürs Auf- noch fürs Zuklappen)
Könnte man nicht das alte Verhalten dazu addieren?
