### ISSUE TITLE
[result] pagination

### ISSUE THREAD

**Issue by lbenedix** [nbi-opendata/videbligo#7]
pagination

**Comment by hanintalal** [comment]
viel Erfolg ktugan  , hab damit angefangen aber noch nicht fertig .brauchte Hilfe von Lukas ,weil ich das Problem beim Code nicht erkannt habe , Aber tja Danke

**Comment by lbenedix** [comment]
ist erstmal erledigt, müsste dann noch hübscher gemacht werden
